version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
    steps:
      - checkout
      - run:
            name: Build
            command: dotnet publish --configuration Release --output build
      - run: 
            name: Publish
            command: |
                cd build/BadActor/dist
                sed -i 's:<base href="/" />:<base href="/BadActor-Blazer/" />:g' index.html
                git config --global user.name "Eric Wehrly"
                git config --global user.email "eric@disruptiontheory.com"
                git init
                git checkout -b gh-pages
                git add -A
                git commit -m "circleCI push that needs build number"
                git push -f https://github.com/EricWehrly/BadActor-Blazer.git gh-pages
